[package]
name = "registmily"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.4.8"
git2 = "0.14.1"
hyper = "0.14.17"
serde = "1.0.136"
tokio = { version = "1.17.0", features = ["full"] }

tracing = "0.1.31"
tracing-subscriber = "0.3.9"